In [1]:
import pandas as pd

In [2]:
credits_df = pd.read_csv("tmdb_5000_credits.csv")
movies_df = pd.read_csv("tmdb_5000_movies.csv")

In [3]:
credits_df.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
(credits_df["cast"][3])

'[{"cast_id": 2, "character": "Bruce Wayne / Batman", "credit_id": "52fe4781c3a36847f8139869", "gender": 2, "id": 3894, "name": "Christian Bale", "order": 0}, {"cast_id": 8, "character": "Alfred Pennyworth", "credit_id": "52fe4781c3a36847f8139881", "gender": 2, "id": 3895, "name": "Michael Caine", "order": 1}, {"cast_id": 5, "character": "James Gordon", "credit_id": "52fe4781c3a36847f8139875", "gender": 2, "id": 64, "name": "Gary Oldman", "order": 2}, {"cast_id": 3, "character": "Selina Kyle / Catwoman", "credit_id": "52fe4781c3a36847f813986d", "gender": 1, "id": 1813, "name": "Anne Hathaway", "order": 3}, {"cast_id": 4, "character": "Bane", "credit_id": "52fe4781c3a36847f8139871", "gender": 2, "id": 2524, "name": "Tom Hardy", "order": 4}, {"cast_id": 15, "character": "Miranda Tate", "credit_id": "52fe4781c3a36847f813988d", "gender": 1, "id": 8293, "name": "Marion Cotillard", "order": 5}, {"cast_id": 6, "character": "Blake", "credit_id": "52fe4781c3a36847f8139879", "gender": 2, "id": 24045, "name": "Joseph Gordon-Levitt", "order": 6}, {"cast_id": 7, "character": "Lucius Fox", "credit_id": "52fe4781c3a36847f813987d", "gender": 2, "id": 192, "name": "Morgan Freeman", "order": 7}, {"cast_id": 46, "character": "Dr. Jonathan Crane / Scarecrow", "credit_id": "52fe4781c3a36847f8139939", "gender": 2, "id": 2037, "name": "Cillian Murphy", "order": 8}, {"cast_id": 9, "character": "Jen", "credit_id": "52fe4781c3a36847f8139885", "gender": 1, "id": 36594, "name": "Juno Temple", "order": 9}, {"cast_id": 47, "character": "Ra\'s Al Ghul", "credit_id": "52fe4781c3a36847f813993d", "gender": 2, "id": 3896, "name": "Liam Neeson", "order": 10}, {"cast_id": 43, "character": "Deputy Commissioner Foley", "credit_id": "52fe4781c3a36847f813992d", "gender": 2, "id": 8654, "name": "Matthew Modine", "order": 11}, {"cast_id": 45, "character": "Dr. Pavel", "credit_id": "52fe4781c3a36847f8139935", "gender": 2, "id": 16607, "name": "Alon Aboutboul", "order": 12}, {"cast_id": 49, "character": "Daggett", "credit_id": "52fe4782c3a36847f8139945", "gender": 2, "id": 77335, "name": "Ben Mendelsohn", "order": 13}, {"cast_id": 10, "character": "The Mayor", "credit_id": "52fe4781c3a36847f8139889", "gender": 2, "id": 21316, "name": "Nestor Carbonell", "order": 14}, {"cast_id": 36, "character": "Young Ra\'s Al Ghul", "credit_id": "52fe4781c3a36847f8139909", "gender": 0, "id": 928532, "name": "Josh Pence", "order": 15}, {"cast_id": 42, "character": "Prisoner", "credit_id": "52fe4781c3a36847f8139929", "gender": 0, "id": 71010, "name": "Tom Conti", "order": 16}, {"cast_id": 44, "character": "Young Talia Al Ghul", "credit_id": "52fe4781c3a36847f8139931", "gender": 1, "id": 125025, "name": "Joey King", "order": 17}, {"cast_id": 48, "character": "Mercenary Security #1", "credit_id": "52fe4781c3a36847f8139941", "gender": 2, "id": 211521, "name": "Warren Brown", "order": 18}, {"cast_id": 50, "character": "Captain Jones", "credit_id": "52fe4782c3a36847f8139949", "gender": 2, "id": 10582, "name": "Daniel Sunjata", "order": 19}, {"cast_id": 52, "character": "Special Ops Sergeant", "credit_id": "52fe4782c3a36847f8139951", "gender": 0, "id": 224365, "name": "Sam Kennard", "order": 20}, {"cast_id": 53, "character": "Hooded Man #2", "credit_id": "53ab5495c3a3684bb900059a", "gender": 0, "id": 1334307, "name": "Aliash Tepina", "order": 21}, {"cast_id": 54, "character": "Caterer", "credit_id": "53ab59d40e0a267622000761", "gender": 0, "id": 1334308, "name": "Nick Julian", "order": 22}, {"cast_id": 55, "character": "Maid", "credit_id": "53ab5ba70e0a26761f000715", "gender": 1, "id": 1334309, "name": "Miranda Nolan", "order": 23}, {"cast_id": 174, "character": "Maid", "credit_id": "562196c8c3a3680e190096a0", "gender": 0, "id": 1172491, "name": "Claire Julien", "order": 24}, {"cast_id": 56, "character": "CIA Op", "credit_id": "53e761100e0a266f9d00176c", "gender": 2, "id": 49735, "name": "Aidan Gillen", "order": 25}, {"cast_id": 172, "character": "Stryver", "credit_id": "5621963e92514171d4009562", "gender": 0, "id": 39659, "name": "Burn Gorman", "order": 26}, {"cast_id": 173, "character": "Congressman", "credit_id": "5621969dc3a3680e0e009e97", "gender": 2, "id": 16841, "name": "Brett Cullen", "order": 27}, {"cast_id": 175, "character": "Ross", "credit_id": "56219708c3a3680e190096a9", "gender": 2, "id": 22075, "name": "Reggie Lee", "order": 28}, {"cast_id": 176, "character": "DWP Man", "credit_id": "56219739c3a3680e1d009ba6", "gender": 2, "id": 159879, "name": "Joseph Lyle Taylor", "order": 29}, {"cast_id": 177, "character": "Fr. Reilly", "credit_id": "56219752c3a3680e10009290", "gender": 2, "id": 8191, "name": "Chris Ellis", "order": 30}, {"cast_id": 179, "character": "SWAT in Dive Bar", "credit_id": "562197d3c3a3680e1d009bc0", "gender": 2, "id": 1240417, "name": "Duane Henry", "order": 31}, {"cast_id": 180, "character": "SWAT in Alley", "credit_id": "562197eb92514171c50096df", "gender": 0, "id": 1218818, "name": "James Harvey Ward", "order": 32}, {"cast_id": 181, "character": "Cop in Manhole", "credit_id": "562198019251411e1f004568", "gender": 2, "id": 84754, "name": "Gonzalo Menendez", "order": 33}, {"cast_id": 365, "character": "Sewer Thug #1", "credit_id": "5744667fc3a3681233001525", "gender": 2, "id": 1473276, "name": "Cameron Jack", "order": 34}, {"cast_id": 182, "character": "Sewer Thug #2", "credit_id": "5621987ec3a3686868003d9a", "gender": 2, "id": 1364324, "name": "Lex Daniel", "order": 35}, {"cast_id": 183, "character": "Mark", "credit_id": "562198cd92514171cd009658", "gender": 2, "id": 1473749, "name": "Tyler Dean Flores", "order": 36}, {"cast_id": 184, "character": "Doctor", "credit_id": "5621991192514171d000960d", "gender": 2, "id": 539, "name": "Thomas Lennon", "order": 37}, {"cast_id": 185, "character": "Yuppie", "credit_id": "5621997192514171d0009625", "gender": 0, "id": 158484, "name": "Trevor White", "order": 38}, {"cast_id": 186, "character": "Allen", "credit_id": "56219994c3a368240d0028d5", "gender": 2, "id": 10689, "name": "Rob Brown", "order": 39}, {"cast_id": 187, "character": "Exchange Security Chief", "credit_id": "562199b492514171d0009634", "gender": 2, "id": 9632, "name": "Fredric Lehne", "order": 40}, {"cast_id": 188, "character": "Female Security Guard", "credit_id": "562199dc92514171d000963c", "gender": 0, "id": 1205900, "name": "Courtney Munch", "order": 41}, {"cast_id": 189, "character": "Paparazzi #1", "credit_id": "56219a2ac3a368240d0028ee", "gender": 2, "id": 1403768, "name": "Chris Hill", "order": 42}, {"cast_id": 190, "character": "Paparazzi #2", "credit_id": "56219a3fc3a3680e16008b49", "gender": 2, "id": 1465242, "name": "Travis Guba", "order": 43}, {"cast_id": 191, "character": "Rich Twit", "credit_id": "56219a6cc3a3680e1900973e", "gender": 2, "id": 141014, "name": "Jay Benedict", "order": 44}, {"cast_id": 192, "character": "Officer Simon Jansen", "credit_id": "56219aadc3a3686868003e03", "gender": 2, "id": 32363, "name": "Will Estes", "order": 45}, {"cast_id": 193, "character": "Shoe Shine Man at GSE", "credit_id": "56219acc92514171c500975b", "gender": 2, "id": 21182, "name": "David Dayan Fisher", "order": 46}, {"cast_id": 194, "character": "Trader #1", "credit_id": "56219b32c3a368240d002927", "gender": 2, "id": 83271, "name": "Glen Powell", "order": 47}, {"cast_id": 195, "character": "Trader #3", "credit_id": "56219b86c3a3680e10009379", "gender": 2, "id": 535, "name": "Russ Fega", "order": 48}, {"cast_id": 196, "character": "Valet at Museum", "credit_id": "56219ba8c3a3680e10009383", "gender": 2, "id": 1226016, "name": "Andres Perez-Molina", "order": 49}, {"cast_id": 197, "character": "Veteran Cop", "credit_id": "56219bc6c3a368240d002952", "gender": 2, "id": 15011, "name": "Brent Briscoe", "order": 50}, {"cast_id": 198, "character": "Fredericks", "credit_id": "56219bec92514171d400967b", "gender": 2, "id": 70225, "name": "John Nolan", "order": 51}, {"cast_id": 199, "character": "2 Star Air Force General", "credit_id": "56219c1c9251413a740041a2", "gender": 2, "id": 24627, "name": "Oliver Cotton", "order": 52}, {"cast_id": 200, "character": "Airport Cop", "credit_id": "56219c3d92514171d400968e", "gender": 0, "id": 142290, "name": "Mark Killeen", "order": 53}, {"cast_id": 201, "character": "Analyst #1", "credit_id": "56219c6ac3a3680e1d009cb3", "gender": 0, "id": 1377686, "name": "Sarah Goldberg", "order": 54}, {"cast_id": 202, "character": "Analyst #2", "credit_id": "56219c86c3a3680e1d009cbb", "gender": 2, "id": 550549, "name": "John MacMillan", "order": 55}, {"cast_id": 203, "character": "Army Captain at Bridge", "credit_id": "56219cf9c3a3680e100093c7", "gender": 2, "id": 21505, "name": "Robert Wisdom", "order": 56}, {"cast_id": 204, "character": "Cement Truck Driver", "credit_id": "56219d18c3a3680e16008bd4", "gender": 2, "id": 98804, "name": "Ronnie Gene Blevins", "order": 57}, {"cast_id": 205, "character": "CIA Analyst", "credit_id": "56219d3d92514171d40096d2", "gender": 0, "id": 1386824, "name": "John Hollingworth", "order": 58}, {"cast_id": 206, "character": "Cop with Gordon", "credit_id": "56219d5dc3a3686868003e71", "gender": 2, "id": 31362, "name": "Ian Bohen", "order": 59}, {"cast_id": 207, "character": "Blind Prisoner", "credit_id": "56219d7ec3a3680e1d009ce9", "gender": 2, "id": 145313, "name": "Uri Gavriel", "order": 60}, {"cast_id": 208, "character": "Ex-Prisoner at River", "credit_id": "56219d9f9251417f470073a3", "gender": 2, "id": 53252, "name": "Noel Gugliemi", "order": 61}, {"cast_id": 209, "character": "Gangbanger", "credit_id": "56219dce9251417f470073b0", "gender": 2, "id": 24202, "name": "Hector Atreyu Ruiz", "order": 62}, {"cast_id": 210, "character": "Huge Inmate", "credit_id": "56219dfdc3a3680e2000a3c3", "gender": 0, "id": 1301187, "name": "Patrick Cox", "order": 63}, {"cast_id": 211, "character": "Kid with Apple", "credit_id": "56219e22c3a3680e2000a3cc", "gender": 2, "id": 204191, "name": "Aramis Knight", "order": 64}, {"cast_id": 212, "character": "Barsad", "credit_id": "56219e589251413a7400421c", "gender": 2, "id": 40039, "name": "Josh Stewart", "order": 65}, {"cast_id": 213, "character": "President", "credit_id": "56219e78c3a3680e0e00a022", "gender": 2, "id": 21416, "name": "William Devane", "order": 66}, {"cast_id": 214, "character": "Skinny Prisoner", "credit_id": "5621a54cc3a3686868003fcc", "gender": 2, "id": 55411, "name": "David Gyasi", "order": 67}, {"cast_id": 215, "character": "Special Forces #2", "credit_id": "5621a5ae9251413a74004f01", "gender": 2, "id": 1244314, "name": "Patrick Jordan", "order": 68}, {"cast_id": 216, "character": "Mercenary at City Hall", "credit_id": "5621a5f3c3a3680e1d009ef0", "gender": 0, "id": 1286878, "name": "Joshua Elijah Reese", "order": 69}, {"cast_id": 217, "character": "Uniform", "credit_id": "5621a611c3a3680e16008d93", "gender": 2, "id": 6365, "name": "Desmond Harrington", "order": 70}, {"cast_id": 218, "character": "Bomb Truck Driver", "credit_id": "5621a64ac3a3680e100095a7", "gender": 2, "id": 1417415, "name": "Mychael Bates", "order": 71}, {"cast_id": 219, "character": "Wayne\'s Lawyer", "credit_id": "5622804dc3a3680e1d00c2ec", "gender": 2, "id": 941, "name": "Tomas Arana", "order": 72}, {"cast_id": 220, "character": "Applied Sciences Tech #1", "credit_id": "56228076c3a3680e1600ae35", "gender": 0, "id": 1225911, "name": "Peter Holden", "order": 73}, {"cast_id": 221, "character": "Applied Sciences Tech #2", "credit_id": "5622809bc3a3680e0e00c5a4", "gender": 2, "id": 100891, "name": "David Monahan", "order": 74}, {"cast_id": 222, "character": "Lawyer\'s Clerk", "credit_id": "562280bbc3a3680e2000ca5f", "gender": 1, "id": 20469, "name": "Jillian Armenante", "order": 75}, {"cast_id": 223, "character": "Greeter at Museum", "credit_id": "562280fcc3a3680e2000ca68", "gender": 1, "id": 105832, "name": "Aja Evans", "order": 76}, {"cast_id": 224, "character": "Valet at Wayne Enterprises", "credit_id": "56228153c3a3680e1600ae64", "gender": 0, "id": 1355615, "name": "Aldous Davidson", "order": 77}, {"cast_id": 225, "character": "Warden at Blackgate", "credit_id": "562281a49251413a74006fda", "gender": 2, "id": 51930, "name": "Wade Williams", "order": 78}, {"cast_id": 226, "character": "Waiter in Florence Caf\\u00e9", "credit_id": "5623d3a8c3a3680e1600d8e2", "gender": 0, "id": 95577, "name": "Jake Canuso", "order": 79}, {"cast_id": 228, "character": "Janitor at GSE", "credit_id": "5623d47c92514127d4003522", "gender": 0, "id": 1010873, "name": "Massi Furlan", "order": 81}, {"cast_id": 229, "character": "Mercenary Security #4", "credit_id": "5623d4f2c3a3680e1d00f29d", "gender": 2, "id": 26088, "name": "Christopher Judge", "order": 82}, {"cast_id": 230, "character": "Board Member #2", "credit_id": "5623d5329251416b3000153a", "gender": 2, "id": 853194, "name": "Patrick Leahy", "order": 83}, {"cast_id": 231, "character": "Uniform #2", "credit_id": "5623d57192514135b00028d6", "gender": 0, "id": 171606, "name": "Todd Gearhart", "order": 84}, {"cast_id": 232, "character": "Gotham City Police Officer (uncredited)", "credit_id": "5623d5d69251417f4700becf", "gender": 2, "id": 1406682, "name": "Marc Abbink", "order": 85}, {"cast_id": 233, "character": "Young Stock Broker (uncredited)", "credit_id": "56252c5a9251413980001f01", "gender": 0, "id": 1167718, "name": "Isiah Adams", "order": 86}, {"cast_id": 234, "character": "Gotham City Police Officer (uncredited)", "credit_id": "56252cb2c3a3680e1d013497", "gender": 1, "id": 572221, "name": "Charlie Alejandro", "order": 87}, {"cast_id": 235, "character": "Former Upscaler (uncredited)", "credit_id": "56252cf9c3a3680e1d01349c", "gender": 2, "id": 1116933, "name": "Robert Arensen", "order": 88}, {"cast_id": 236, "character": "Angry Mobster / Prisoner (uncredited)", "credit_id": "56252d43c3a3680e2001483e", "gender": 0, "id": 1524158, "name": "Grant Babbitt", "order": 89}, {"cast_id": 237, "character": "Gotham Rogues Fan (uncredited)", "credit_id": "56252d6e9251413980001f2a", "gender": 0, "id": 139188, "name": "Fileena Bahris", "order": 90}, {"cast_id": 238, "character": "Mercenary (uncredited)", "credit_id": "56258b759251413980002af5", "gender": 0, "id": 1075845, "name": "Rick Bolander", "order": 91}, {"cast_id": 239, "character": "Police Officer (uncredited)", "credit_id": "56258bb192514135b000724c", "gender": 0, "id": 1283949, "name": "Kyle Patrick Brennan", "order": 92}, {"cast_id": 240, "character": "Gotham City Police Officer (uncredited)", "credit_id": "56267a109251412f15000873", "gender": 0, "id": 1344943, "name": "Scott Churchson", "order": 93}, {"cast_id": 241, "character": "Gotham Rogues Coach (uncredited)", "credit_id": "56267aeec3a3680e200186f9", "gender": 0, "id": 1240191, "name": "Bill Cowher", "order": 94}, {"cast_id": 242, "character": "Pentagon Navy Petty (uncredited)", "credit_id": "56267bbc9251412f150008ac", "gender": 0, "id": 1359461, "name": "Graham Curry", "order": 95}, {"cast_id": 243, "character": "Reporter (uncredited)", "credit_id": "5626dd3f92514137bb0006c8", "gender": 1, "id": 1163300, "name": "Stephanie Domini Ehlert", "order": 96}, {"cast_id": 244, "character": "Older Upscale Person (uncredited)", "credit_id": "5627ca69c3a3687c52000500", "gender": 0, "id": 93752, "name": "John Farrer", "order": 97}, {"cast_id": 245, "character": "Prisoner / Thug (uncredited)", "credit_id": "5627caafc3a3687c600004b3", "gender": 0, "id": 1343309, "name": "Frank Fata", "order": 98}, {"cast_id": 246, "character": "Stock Broker (uncredited)", "credit_id": "562830b7c3a3684880000421", "gender": 0, "id": 1372419, "name": "Christopher Bryan Gomez", "order": 99}, {"cast_id": 247, "character": "Thug (uncredited)", "credit_id": "562831229251414cdd000442", "gender": 0, "id": 1502323, "name": "Vito Grassi", "order": 100}, {"cast_id": 248, "character": "Stockbroker in Snipers Scoop - Stock Exchange (uncredited)", "credit_id": "5628314ec3a368487d00043e", "gender": 2, "id": 1509064, "name": "Michael Wren Gucciardo", "order": 101}, {"cast_id": 249, "character": "Prisoner (uncredited)", "credit_id": "56291c98c3a368487a0023d6", "gender": 2, "id": 1525392, "name": "Sam Harris", "order": 102}, {"cast_id": 250, "character": "Police Officer (uncredited)", "credit_id": "56291cdc9251414ccf002762", "gender": 0, "id": 1365976, "name": "Ed Heavey", "order": 103}, {"cast_id": 251, "character": "Gotham Police Officer / Fan (uncredited)", "credit_id": "56291d5cc3a368488c002830", "gender": 2, "id": 1098036, "name": "John W. Iwanonkiw", "order": 104}, {"cast_id": 252, "character": "Gordon\'s Cop #4 (uncredited)", "credit_id": "56291dec9251414cd20026d0", "gender": 0, "id": 1354413, "name": "Cindy Jackson", "order": 105}, {"cast_id": 253, "character": "Boom Operator News Crew (uncredited)", "credit_id": "56291ecc9251414cd800251f", "gender": 0, "id": 123875, "name": "Daniel Jordano", "order": 106}, {"cast_id": 254, "character": "Gothamite (uncredited)", "credit_id": "562974c7c3a3681b5e000691", "gender": 0, "id": 127060, "name": "William Kania", "order": 107}, {"cast_id": 255, "character": "Gotham Rogues Fan (uncredited)", "credit_id": "562974f39251412853000708", "gender": 0, "id": 1388256, "name": "Tiffany Kemp", "order": 108}, {"cast_id": 256, "character": "Stock Broker (uncredited)", "credit_id": "562975e8c3a3681b4b00067b", "gender": 0, "id": 1241239, "name": "Sun Jae Kim", "order": 109}, {"cast_id": 257, "character": "Thug (uncredited)", "credit_id": "56297620c3a3681b5e0006c6", "gender": 0, "id": 1378466, "name": "Hrvoje Klecz", "order": 110}, {"cast_id": 258, "character": "Wall Street Broker (uncredited)", "credit_id": "5629768a9251412845000609", "gender": 0, "id": 1264686, "name": "Alex Kruz", "order": 111}, {"cast_id": 259, "character": "Gotham City Police Officer (uncredited)", "credit_id": "562a6fcf9251414ab7000d11", "gender": 0, "id": 1169299, "name": "Tyler La Marr", "order": 112}, {"cast_id": 260, "character": "Thug (uncredited)", "credit_id": "562a7046c3a3681b5c002691", "gender": 2, "id": 1269611, "name": "LeJon", "order": 113}, {"cast_id": 261, "character": "Gotham City Police Officer (uncredited)", "credit_id": "562a706fc3a3681b610028d9", "gender": 0, "id": 1446471, "name": "Paul Jude Letersky", "order": 114}, {"cast_id": 262, "character": "Prisoner (uncredited)", "credit_id": "562a70e5c3a3681b520027e1", "gender": 0, "id": 1188950, "name": "Joe Lipari", "order": 115}, {"cast_id": 263, "character": "Tourist (uncredited)", "credit_id": "562a7123c3a3681b5900267c", "gender": 0, "id": 1383091, "name": "Silvia Lombardo", "order": 116}, {"cast_id": 264, "character": "Gotham Rogues Fan (uncredited)", "credit_id": "562ad1bd9251414006001a31", "gender": 0, "id": 1480128, "name": "Jorge Mardel", "order": 117}, {"cast_id": 265, "character": "Gotham Rogues Fan (uncredited)", "credit_id": "562ad293925141284a0032ba", "gender": 0, "id": 1174970, "name": "Cale McConnell", "order": 118}, {"cast_id": 266, "character": "Gotham City Police Officer (uncredited)", "credit_id": "562ad2c6c3a3681b4d003b12", "gender": 0, "id": 127063, "name": "David Dale McCue", "order": 119}, {"cast_id": 267, "character": "Gotham Rogues Fan (uncredited)", "credit_id": "562ad2f49251412857003295", "gender": 1, "id": 1480130, "name": "Tiffany Sander McKenzie", "order": 120}, {"cast_id": 268, "character": "Angry Mobster (uncredited)", "credit_id": "562ad32f92514128530033a7", "gender": 0, "id": 1505308, "name": "Allen Merritt", "order": 121}, {"cast_id": 269, "character": "Wayne Enterprises Security (uncredited)", "credit_id": "562ad36ac3a3681b4d003b44", "gender": 0, "id": 1509148, "name": "Olan Montgomery", "order": 122}, {"cast_id": 270, "character": "Mercenary (uncredited)", "credit_id": "562ad3cdc3a3681b4d003b5b", "gender": 0, "id": 122339, "name": "Alex Moore", "order": 123}, {"cast_id": 271, "character": "Gotham City Police Officer (uncredited)", "credit_id": "562bb8699251412853005938", "gender": 0, "id": 93778, "name": "Shane Nolan", "order": 124}, {"cast_id": 272, "character": "Prisoner / Thug (uncredited)", "credit_id": "562bb8a1c3a3681b54005616", "gender": 0, "id": 1205749, "name": "Jackson Nunn", "order": 125}

In [9]:
movies_df

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [10]:
movies_df["genres"][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [12]:
movies_df["keywords"][3]

'[{"id": 849, "name": "dc comics"}, {"id": 853, "name": "crime fighter"}, {"id": 949, "name": "terrorist"}, {"id": 1308, "name": "secret identity"}, {"id": 1437, "name": "burglar"}, {"id": 3051, "name": "hostage drama"}, {"id": 3562, "name": "time bomb"}, {"id": 6969, "name": "gotham city"}, {"id": 7002, "name": "vigilante"}, {"id": 9665, "name": "cover-up"}, {"id": 9715, "name": "superhero"}, {"id": 9990, "name": "villainess"}, {"id": 10044, "name": "tragic hero"}, {"id": 13015, "name": "terrorism"}, {"id": 14796, "name": "destruction"}, {"id": 18933, "name": "catwoman"}, {"id": 156082, "name": "cat burglar"}, {"id": 156395, "name": "imax"}, {"id": 173272, "name": "flood"}, {"id": 179093, "name": "criminal underworld"}, {"id": 230775, "name": "batman"}]'

    - Create a database
        - Movie name
            - Director
            - Cast ( top 3-4 cast)
            - keywords
            - genres
            - tagline
            - overview
    - Text Cleaning
    - Text Representation / Convert the text data to numerical data
    - We will use distance between the movies to calculate which movies are closer to each other

    Dark Knight --->   [3.4, 2.4, 1.2, 0.9]
    Batman Begins ---> [2.3, 5.6, 8.9. 0.9]

In [63]:
df = movies_df.merge(credits_df, left_on="id", right_on="movie_id")
df

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_x,vote_average,vote_count,movie_id,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,9367,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,72766,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,231617,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,126186,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,25975,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [64]:
selected_columns = ['original_title', 'genres',  'keywords', 'overview', 'tagline',  'cast', 'crew']

In [65]:
df = df[selected_columns]
df

,original_title,genres,keywords,overview,tagline,cast,crew
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,A Plan No One Escapes,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,The Legend Ends,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","Lost in our world, found in another.","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4798,El Mariachi,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...",El Mariachi just wants to play his guitar and ...,"He didn't come looking for trouble, but troubl...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,Newlyweds,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],A newlywed couple's honeymoon is upended by th...,A newlywed couple's honeymoon is upended by th...,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,"Signed, Sealed, Delivered","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","""Signed, Sealed, Delivered"" introduces a dedic...",NaN,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,Shanghai Calling,[],[],When ambitious New York attorney Sam is sent t...,A New Yorker in Shanghai,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,My Date with Drew,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",Ever since the second grade when he first saw ...,NaN,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [66]:
from ast import literal_eval

In [67]:
literal_eval('{"a":123, "b":456}')

{'a': 123, 'b': 456}

In [68]:
[x["name"] for x in  literal_eval(df["genres"][0])]

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [69]:
df["genres"]

0       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3       [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
                              ...
4798    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4799    [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4800    [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4801                                                   []
4802                  [{"id": 99, "name": "Documentary"}]
Name: genres, Length: 4803, dtype: object

In [70]:
df["genres"] = df["genres"].apply(lambda x: [d["name"] for d in literal_eval(x)])
df["keywords"] = df["keywords"].apply(lambda x: [d["name"] for d in literal_eval(x)])

/var/folders/st/b0hjmx2s42dbbvjsct0_5c300000gn/T/ipykernel_8767/2157240200.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["genres"] = df["genres"].apply(lambda x: [d["name"] for d in literal_eval(x)])
/var/folders/st/b0hjmx2s42dbbvjsct0_5c300000gn/T/ipykernel_8767/2157240200.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["keywords"] = df["keywords"].apply(lambda x: [d["name"] for d in literal_eval(x)])

In [71]:
df["cast"] = df["cast"].apply(lambda x: [d["name"] for d in literal_eval(x)][:3])

/var/folders/st/b0hjmx2s42dbbvjsct0_5c300000gn/T/ipykernel_8767/4212260742.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["cast"] = df["cast"].apply(lambda x: [d["name"] for d in literal_eval(x)][:3])

In [72]:
df["crew"]= df["crew"].apply(lambda x: [d["name"] for d in  literal_eval(df["crew"][0]) if d["job"]=="Director"])

/var/folders/st/b0hjmx2s42dbbvjsct0_5c300000gn/T/ipykernel_8767/3886387188.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["crew"]= df["crew"].apply(lambda x: [d["name"] for d in  literal_eval(df["crew"][0]) if d["job"]=="Director"])

In [73]:
df.isna().sum()

original_title      0
genres              0
keywords            0
overview            3
tagline           844
cast                0
crew                0
dtype: int64

In [74]:
df = df.dropna()
df = df.drop("tagline", axis = 1)

In [76]:
df["overview"] = df["overview"].apply(lambda x: x.split())

In [77]:
df

,original_title,genres,keywords,overview,cast,crew
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[James Cameron]
2,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[James Cameron]
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[James Cameron]
4,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[James Cameron]
...,...,...,...,...,...,...
4795,Bang,[Drama],"[gang, audition, police fake, homeless, actress]","[A, young, woman, in, L.A., is, having, a, bad...","[Darling Narita, Peter Greene, Michael Newland]",[James Cameron]
4796,Primer,"[Science Fiction, Drama, Thriller]","[distrust, garage, identity crisis, time trave...","[Friends/fledgling, entrepreneurs, invent, a, ...","[Shane Carruth, David Sullivan, Casey Gooden]",[James Cameron]
4798,El Mariachi,"[Action, Crime, Thriller]","[united states–mexico barrier, legs, arms, pap...","[El, Mariachi, just, wants, to, play, his, gui...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[James Cameron]
4799,Newlyweds,"[Comedy, Romance]",[],"[A, newlywed, couple's, honeymoon, is, upended...","[Edward Burns, Kerry Bishé, Marsha Dietlein]",[James Cameron]
4801,Shanghai Calling,[],[],"[When, ambitious, New, York, attorney, Sam, is...","[Daniel Henney, Eliza Coupe, Bill Paxton]",[James Cameron]

In [82]:
def remove_space(text):
    return [x.replace(" ", "") for x in text]

In [83]:
remove_space("space war")

['s', 'p', 'a', 'c', 'e', '', 'w', 'a', 'r']

In [84]:
df["genres"] = df["genres"].apply(remove_space)
df["keywords"] = df["keywords"].apply(remove_space)
df["cast"] = df["cast"].apply(remove_space)
df["crew"] = df["crew"].apply(remove_space)

In [85]:
df

,original_title,genres,keywords,overview,cast,crew
0,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[JamesCameron]
2,Spectre,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[JamesCameron]
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[JamesCameron]
4,John Carter,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[JamesCameron]
...,...,...,...,...,...,...
4795,Bang,[Drama],"[gang, audition, policefake, homeless, actress]","[A, young, woman, in, L.A., is, having, a, bad...","[DarlingNarita, PeterGreene, MichaelNewland]",[JamesCameron]
4796,Primer,"[ScienceFiction, Drama, Thriller]","[distrust, garage, identitycrisis, timetravel,...","[Friends/fledgling, entrepreneurs, invent, a, ...","[ShaneCarruth, DavidSullivan, CaseyGooden]",[JamesCameron]
4798,El Mariachi,"[Action, Crime, Thriller]","[unitedstates–mexicobarrier, legs, arms, paper...","[El, Mariachi, just, wants, to, play, his, gui...","[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[JamesCameron]
4799,Newlyweds,"[Comedy, Romance]",[],"[A, newlywed, couple's, honeymoon, is, upended...","[EdwardBurns, KerryBishé, MarshaDietlein]",[JamesCameron]
4801,Shanghai Calling,[],[],"[When, ambitious, New, York, attorney, Sam, is...","[DanielHenney, ElizaCoupe, BillPaxton]",[JamesCameron]

In [87]:
df.columns

Index(['original_title', 'genres', 'keywords', 'overview', 'cast', 'crew',
       'tag'],
      dtype='object')

In [86]:
df["tag"] = df["genres"]+df["keywords"]+df["overview"]+df["cast"]+df["crew"]

In [89]:
df = df[["original_title", "tag"]]

In [90]:
df

,original_title,tag
0,Avatar,"[Action, Adventure, Fantasy, ScienceFiction, c..."
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action, ocean, drugabuse,..."
2,Spectre,"[Action, Adventure, Crime, spy, basedonnovel, ..."
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller, dccomics, cri..."
4,John Carter,"[Action, Adventure, ScienceFiction, basedonnov..."
...,...,...
4795,Bang,"[Drama, gang, audition, policefake, homeless, ..."
4796,Primer,"[ScienceFiction, Drama, Thriller, distrust, ga..."
4798,El Mariachi,"[Action, Crime, Thriller, unitedstates–mexicob..."
4799,Newlyweds,"[Comedy, Romance, A, newlywed, couple's, honey..."
4801,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."

In [91]:
df["tag"] = df["tag"].apply(lambda x: " ".join(x))
df

/var/folders/st/b0hjmx2s42dbbvjsct0_5c300000gn/T/ipykernel_8767/3143706675.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["tag"] = df["tag"].apply(lambda x: " ".join(x))

,original_title,tag
0,Avatar,Action Adventure Fantasy ScienceFiction cultur...
1,Pirates of the Caribbean: At World's End,Adventure Fantasy Action ocean drugabuse exoti...
2,Spectre,Action Adventure Crime spy basedonnovel secret...
3,The Dark Knight Rises,Action Crime Drama Thriller dccomics crimefigh...
4,John Carter,Action Adventure ScienceFiction basedonnovel m...
...,...,...
4795,Bang,Drama gang audition policefake homeless actres...
4796,Primer,ScienceFiction Drama Thriller distrust garage ...
4798,El Mariachi,Action Crime Thriller unitedstates–mexicobarri...
4799,Newlyweds,Comedy Romance A newlywed couple's honeymoon i...
4801,Shanghai Calling,When ambitious New York attorney Sam is sent t...

In [94]:
df.iloc[0]["tag"]

'Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

    Steps to follow:
        - Clean the data 
            - remove stop words
            - punctuations
            - remove digits
        - Build vector representation 
            - Count Vectorizer
            - Tfidf vectorizer
            - Word2ec ( spacy)
            
        - Build a similarity matrix (cosine similarity)
        - Make a recommendation based on the similarity matrix

In [96]:
import spacy
nlp = spacy.load("en_core_web_lg")

In [97]:
def clean_text(text):
    
    doc = nlp(text)
    clean_text  = []
    for token in doc:
        if not token.is_stop and not token.is_punct and not token.is_space:
            clean_text.append(token.lemma_.lower()) # lemmatization and converting to lower case
            
    return " ".join(clean_text)

In [106]:
def clean_text2(text):
    
    doc = nlp(text)
    clean_text  = []
    for token in doc:
        if token.pos_ in ["ADJ","NOUN"]:
            if not token.is_stop and not token.is_punct and not token.is_space:
                clean_text.append(token.lemma_.lower()) # lemmatization and converting to lower case
            
    return " ".join(clean_text)

In [107]:
clean_text2("I am very happy going to school. I am also sad. I am following someone. I am trying to do")

'happy go school sad follow try'

In [98]:
df["tag"]= df["tag"].apply(clean_text)

/var/folders/st/b0hjmx2s42dbbvjsct0_5c300000gn/T/ipykernel_8767/297754589.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["tag"]= df["tag"].apply(clean_text)

In [99]:
df

,original_title,tag
0,Avatar,action adventure fantasy sciencefiction cultur...
1,Pirates of the Caribbean: At World's End,adventure fantasy action ocean drugabuse exoti...
2,Spectre,action adventure crime spy basedonnovel secret...
3,The Dark Knight Rises,action crime drama thriller dccomic crimefight...
4,John Carter,action adventure sciencefiction basedonnovel m...
...,...,...
4795,Bang,drama gang audition policefake homeless actres...
4796,Primer,sciencefiction drama thriller distrust garage ...
4798,El Mariachi,action crime thriller unitedstate mexicobarri ...
4799,Newlyweds,comedy romance newlywed couple honeymoon upend...
4801,Shanghai Calling,ambitious new york attorney sam send shanghai ...

In [100]:
df.iloc[0]["tag"]

'action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelation mindandsoul 3d 22nd century paraplegic marine dispatch moon pandora unique mission tear follow order protect alien civilization samworthington zoesaldana sigourneyweaver jamescameron'

## Vectorisation

In [111]:
df.shape

(3959, 2)

In [108]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [136]:
vector_array = TfidfVectorizer(max_features=2000).fit_transform(df["tag"])

In [137]:
vector_array

<3959x2000 sparse matrix of type '<class 'numpy.float64'>'
	with 99151 stored elements in Compressed Sparse Row format>

In [138]:
pd.DataFrame(vector_array.toarray())

,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.074622,0.000000,0.000000,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3954,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.167448,0.0,0.0,0.0
3955,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0
3956,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0
3957,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0
3958,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.183128,0.0,0.0,0.000000,0.135901,0.000000,0.0,0.0,0.0

In [139]:
from sklearn.metrics.pairwise import cosine_similarity

In [140]:
m_m_similarity = cosine_similarity(vector_array)

In [141]:
m_m_similarity.shape

(3959, 3959)

In [142]:
df.columns

Index(['original_title', 'tag'], dtype='object')

In [143]:
similarity_df = pd.DataFrame(m_m_similarity, columns=df["original_title"], index=df["original_title"])
similarity_df

original_title,Avatar,Pirates of the Caribbean: At World's End,Spectre,The Dark Knight Rises,John Carter,Spider-Man 3,Tangled,Avengers: Age of Ultron,Harry Potter and the Half-Blood Prince,Batman v Superman: Dawn of Justice,...,Pink Flamingos,Clean,Tin Can Man,キュア,On The Downlow,Bang,Primer,El Mariachi,Newlyweds,Shanghai Calling
original_title,,,,,,,,,,,,,,,,,,,,,
Avatar,1.000000,0.034821,0.042862,0.060918,0.140402,0.064496,0.006266,0.114421,0.030788,0.034460,...,0.001607,0.002381,0.001970,0.001071,0.002197,0.033572,0.081323,0.008620,0.024744,0.009483
Pirates of the Caribbean: At World's End,0.034821,1.000000,0.019689,0.006007,0.049307,0.090488,0.006844,0.059056,0.033630,0.037642,...,0.001755,0.002601,0.017669,0.001170,0.002400,0.008990,0.001774,0.009415,0.003370,0.001292
Spectre,0.042862,0.019689,1.000000,0.019216,0.034375,0.034957,0.006410,0.103619,0.046782,0.022347,...,0.062724,0.002436,0.002015,0.036344,0.067706,0.001025,0.001661,0.019468,0.003157,0.025580
The Dark Knight Rises,0.060918,0.006007,0.019216,1.000000,0.017801,0.025708,0.022202,0.028426,0.035913,0.257298,...,0.017108,0.006514,0.001290,0.025572,0.006010,0.019778,0.009707,0.023706,0.002021,0.067057
John Carter,0.140402,0.049307,0.034375,0.017801,1.000000,0.028043,0.045007,0.108324,0.010966,0.040731,...,0.001346,0.001995,0.001650,0.016073,0.019523,0.000840,0.014342,0.007220,0.002585,0.000990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Bang,0.033572,0.008990,0.001025,0.019778,0.000840,0.027092,0.067191,0.015345,0.001244,0.050596,...,0.001211,0.007499,0.038826,0.000807,0.074065,1.000000,0.036320,0.030079,0.002326,0.016104
Primer,0.081323,0.001774,0.001661,0.009707,0.014342,0.064199,0.066622,0.115656,0.028231,0.019749,...,0.031458,0.012147,0.002406,0.007783,0.011207,0.036320,1.000000,0.038199,0.003769,0.001444
El Mariachi,0.008620,0.009415,0.019468,0.023706,0.007220,0.006321,0.030696,0.046896,0.066806,0.014046,...,0.014231,0.002444,0.031207,0.089260,0.002255,0.030079,0.038199,1.000000,0.003167,0.010280
Newlyweds,0.024744,0.003370,0.003157,0.002021,0.002585,0.002263,0.002302,0.002744,0.003829,0.002730,...,0.099696,0.005527,0.004572,0.002485,0.005099,0.002326,0.003769,0.003167,1.000000,0.022010
Shanghai Calling,0.009483,0.001292,0.025580,0.067057,0.000990,0.008565,0.020035,0.001052,0.044935,0.010335,...,0.001429,0.002118,0.036790,0.008066,0.001954,0.016104,0.001444,0.010280,0.022010,1.000000

In [144]:
similarity_df["The Dark Knight Rises"].sort_values(ascending=False)[1:15]

original_title
The Dark Knight                            0.495995
Batman Returns                             0.402191
Batman Forever                             0.349024
Batman: The Dark Knight Returns, Part 2    0.333379
Batman & Robin                             0.289911
Batman Begins                              0.288146
Batman                                     0.284257
Batman v Superman: Dawn of Justice         0.257298
Slow Burn                                  0.256957
Carlos                                     0.200785
Defendor                                   0.196485
JFK                                        0.185026
Kick-Ass 2                                 0.169571
Teenage Mutant Ninja Turtles               0.163645
Name: The Dark Knight Rises, dtype: float64

In [160]:
similarity_df.index

Index(['Avatar', 'Pirates of the Caribbean: At World's End', 'Spectre',
       'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled',
       'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince',
       'Batman v Superman: Dawn of Justice',
       ...
       'Pink Flamingos', 'Clean', 'Tin Can Man', 'キュア', 'On The Downlow',
       'Bang', 'Primer', 'El Mariachi', 'Newlyweds', 'Shanghai Calling'],
      dtype='object', name='original_title', length=3959)

In [165]:
def recommend_movies(movie_name, count= 5):
    try:
        return similarity_df[movie_name].sort_values(ascending=False)[1:count].index.values.tolist()
    except KeyError:
        raise Exception("Movie Recommendations not found. Try with a different movie")

In [168]:
recommend_movies("Spectre", count = 5)

['Quantum of Solace', 'Never Say Never Again', 'Skyfall', 'Octopussy']

In [169]:
similarity_df.to_pickle("/Users/ram/Documents/analytixlabs/2Sep-2023-MLBatch/recommendation_system/similarity_df.pkl")